package com.halenteck.demo.audit;

public enum StudyAuditAction {
    STUDY_CREATED,
    STUDY_UPDATED,
    STUDY_PUBLISHED,
    STUDY_CLOSED,
    STUDY_ARCHIVED,
    COLLABORATOR_ADDED,
    COLLABORATOR_ROLE_CHANGED,
    COLLABORATOR_REMOVED,
    QUIZ_ASSIGNED,
    TASK_ASSIGNED,
    TASK_COMPLETED,
    ARTIFACT_LINKED,
    ARTIFACT_UNLINKED,
    RATING_CRITERION_ADDED,
    RATING_CRITERION_UPDATED,
    RATING_CRITERION_REMOVED,
    INVITE_CREATED,
    INVITE_ACCEPTED,
    AUDIT_LOG_EXPORTED,
    REVIEWER_NOTE_ADDED
}


